# Generated by Django 3.2 on 2021-12-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('email_per', models.EmailField(max_length=60, verbose_name='email_per')),
                ('nbr_heures_totale', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=255, null=True)),
                ('situation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_responsable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_student', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
