# Generated by Django 3.2 on 2021-12-13 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('identifiant', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('nbr_etudiants', models.IntegerField()),
                ('amil_groupe', models.CharField(max_length=255)),
                ('niveau_etude', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('nbr_heures_totale', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('niveau', models.CharField(max_length=255)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groupes', models.ManyToManyField(to='module_enseignant.Groupe')),
            ],
        ),
        migrations.CreateModel(
            name='TravailE',
            fields=[
                ('identifiant', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('date_lancement', models.DateField()),
                ('date_retour', models.DateField()),
                ('nature', models.CharField(max_length=255)),
                ('descriptif', models.CharField(max_length=255)),
                ('piece_jointe_enonce', models.URLField(max_length=255)),
                ('etat', models.CharField(max_length=255)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_enseignant.module')),
            ],
        ),
        migrations.CreateModel(
            name='TravailR',
            fields=[
                ('identifiant', models.AutoField(primary_key=True, serialize=False)),
                ('piece_jointe_rendu', models.URLField(max_length=255)),
                ('evaluation', models.CharField(max_length=255)),
                ('date', models.DateField(max_length=255)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travailE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_enseignant.travaile')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('identifiant', models.AutoField(primary_key=True, serialize=False)),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('numero_salle', models.IntegerField()),
                ('objectif', models.CharField(max_length=255)),
                ('resume', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('etat', models.CharField(max_length=255)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_enseignant.module')),
            ],
        ),
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('identifiant', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('contenu', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_enseignant.seance')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('identifiant', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('motif', models.CharField(max_length=255)),
                ('justificatif', models.CharField(max_length=255)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_enseignant.seance')),
            ],
        ),
    ]
