# Generated by Django 3.2 on 2021-12-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_enseignant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travaile',
            name='piece_jointe_enonce',
            field=models.FileField(max_length=255, upload_to='travailE/'),
        ),
        migrations.AlterField(
            model_name='travailr',
            name='piece_jointe_rendu',
            field=models.FileField(max_length=255, upload_to='travailR/'),
        ),
    ]
