# Generated by Django 3.2 on 2021-12-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_enseignant', '0002_auto_20211214_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='travailr',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
    ]
